version: "3.3"


services: 

  elasticsearch:
    image: ind3x/rpi-elasticsearch
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - './config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - './logs:/usr/share/elasticsearch/logs'

    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  logstash:
    image: ind3x/rpi-logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - './config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'

  kibana:
    image: ind3x/rpi-kibana
    volumes:
      - './config/kibana.yml:/opt/kibana/config/kibana.yml:ro'
    ports:
      - "5601:5601"

  grafana:
    image: grafana/grafana:6.6.2
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

volumes:
  grafana-storage:
